### ISSUE TITLE
Missing code

### ISSUE THREAD

**Issue by pditommaso** [nextflow-io/training#142]
Something looks missing in [section 5.1.2](https://training.nextflow.io/basic_training/channels/#value-channels)

<img width="1548" alt="Screenshot 2023-02-02 at 23 34 53" src="https://user-images.githubusercontent.com/816968/216465258-1f693089-da96-47dd-ac4f-da0985f6e4e7.png">

**Comment by mribeirodantas** [comment]
It's the same way it was before, it's the output of the pipeline above. I will add a line between the two blocks to make it clearer.
