### ISSUE TITLE
Local deployment is failing

### ISSUE THREAD

**Issue by mribeirodantas** [nextflow-io/training#176]
When trying to run
```
docker run --rm -it -p 8000:8000 -v ${PWD}:/docs ghcr.io/nextflow-io/training-mkdocs:latest
```
the following error is printed:
```
ERROR    -  Config value 'plugins': The "i18n" plugin is not installed
```

The remote container image must be rebuilt.
- [x] Fix Dockerfile
- [x] Rebuild + push to container registry

**Comment by mribeirodantas** [comment]
@ewels

**Comment by ewels** [comment]
Hopefully fixed in #178 - shout if it's still not working!

**Comment by mribeirodantas** [comment]
It didn't 😞 https://github.com/nextflow-io/training/pull/178#issuecomment-1435831204

**Comment by ewels** [comment]
That GitHub CI failure is for the other Docker container, not the mkdocs one. Those are two separate errors..

**Comment by mribeirodantas** [comment]
You're right, my bad. I was close this issue and open a new one for the other container image.
