### ISSUE TITLE
Translate Modularization section of the basic training to Portuguese

### ISSUE THREAD

**Issue by mribeirodantas** [nextflow-io/training#190]
Translate the [Modularization section](https://github.com/nextflow-io/training/blob/master/docs/basic_training/modules.md) of the basic training to Portuguese  (preview it [here](https://training.nextflow.io/pt/basic_training/modules/)).

**Comment by mribeirodantas** [comment]
@iaradsouza1 you mentioned you are interested in translating this one, right?

**Comment by iaradsouza1** [comment]
Yes, I'll work on that. Please tell me if there's another section available for translation.
