### ISSUE TITLE
Translate cache and resume section of the basic training to Portuguese

### ISSUE THREAD

**Issue by mribeirodantas** [nextflow-io/training#193]
Translate the [cache and resume section](https://github.com/nextflow-io/training/blob/master/docs/basic_training/cache_and_resume.md) of the basic training to Portuguese (preview [here](https://training.nextflow.io/pt/basic_training/cache_and_resume/)).

**Comment by iaradsouza1** [comment]
I can work on this one.

**Comment by mribeirodantas** [comment]
Great!
