### ISSUE TITLE
nextflow seems to allow multiple variables with the same name in the same scope

### ISSUE THREAD

**Issue by jgbaum** [nextflow-io/training#231]
In the training materials, [section 6.3.5](https://training.nextflow.io/basic_training/processes/#composite-inputs-and-outputs), there's a process that has two input variables called 'sample_id':

```groovy
    input:
    tuple val(sample_id), path(sample_id)
```

The workflow runs through, but this seems like it would result in unpredictable behavior.  Shouldn't the compiler complain about this or am I missing something?

Thanks for your help!

**Comment by mribeirodantas** [comment]
You're correct. Thanks for reporting this! 😉

**Comment by mribeirodantas** [comment]
I just improved the example in the training material. As for Nextflow complaining about this or not, you should open an issue on the [Nextflow GitHub repository](https://github.com/nextflow-io/nextflow) 😄

**Comment by jgbaum** [comment]
Thanks for the quick reply!  I've gone ahead and submitted a new issue here:

https://github.com/nextflow-io/nextflow/issues/3874
