### ISSUE TITLE
gghist.R does not exist in cbcrg/callings-with-gatk:latest

### ISSUE THREAD

**Issue by Xophmeister** [nextflow-io/training#303]
Step 6B in the RNA-seq variant calling pipeline work-through uses the DockerHub container `cbcrg/callings-with-gatk:latest`. This image exists, but it does not contain the executable script `gghist.R`, which is used in the process script. Thus the workflow fails.

**Code**
https://github.com/nextflow-io/training/blob/d46bd35dceb7fa476d681589a8d45ecb7331edea/hands-on/final_main.nf#L309-L338

**Documentation** (first mention; repeated elsewhere in this file)
https://github.com/nextflow-io/training/blob/d46bd35dceb7fa476d681589a8d45ecb7331edea/docs/hands_on/04_implementation.md?plain=1#L1346-L1376

**Comment by Xophmeister** [comment]
...Ah, my mistake, this script should be in the workflow's `bin` directory. It's briefly mentioned in the setup chapter:

https://github.com/nextflow-io/training/blob/d46bd35dceb7fa476d681589a8d45ecb7331edea/docs/hands_on/03_setup.md?plain=1#L23-L48

Maybe this could be made clearer?

**Comment by mribeirodantas** [comment]
You're correct. It should be made more explicit. Thanks, @Xophmeister! 😉

Do you want to have a try with a PR?
