### ISSUE TITLE
Broken link on Deployment Scenarios page

### ISSUE THREAD

**Issue by wasimsandhu** [nextflow-io/training#340]
In the [Deployment scenarios > Cloud deployment > AWS Batch](https://training.nextflow.io/basic_training/executors/#aws-batch) section, the following link is broken:

> The complete details about AWS Batch deployment are available at [this link](https://www.nextflow.io/docs/latest/awscloud.html#aws-batch).

Small typo, looks like it should point to [here](https://www.nextflow.io/docs/latest/aws.html#aws-batch).

**Comment by mribeirodantas** [comment]
Thanks, @wasimsandhu !
