### ISSUE TITLE
Add docs warning for un-desired behaviour when using System.exit()

### ISSUE THREAD

**Issue by dlejeune** [nextflow-io/training#343]
Hey 👋

Not sure if this is the right forum, I'm happy to post somewhere else but I figured I should write this somewhere since I've been debugging this issue for longer than I care to admit. 

I think that the docs should include a section that warns developers about unexpected consequences of using `System.exit(n)` in their code. 

I was trying to prematurely end my workflow to debug the contents of a channel. The code looked like this:

```
workflow TEST{
    // Init the channel. The actual initialisation was more complex, but this serves to illustrate. 
    ch = channel.of(1, 2,3)

    ch.view()

    System.exit(0)

    // Other workflow code that I didn't want executing was after this line
}

```

This code doesn't display anything, I assume because nextflow doesn't get to process the `view()` before the `exit()`. I think there's an open issue about this here, https://github.com/nextflow-io/nextflow/issues/3984 , but as far as I can tell there isn't a recommended way of exiting a script prematurely. 

Anyway. I just want to warn others of this, cause it took me a long time to think of why. Happy to move this to a different location if this isn't the right place, and I'm also happy to write the section in the docs, just want to check if this is the right place to do so :)

**Comment by mribeirodantas** [comment]
The [community forum](https://community.seqera.io) is a better place for such questions. The `exit`* and `error` functions are documented in the official docs of Nextflow (check [here](https://www.nextflow.io/docs/latest/script.html#implicit-functions)).

* `exit` has been recently deprecated in favor of `error`.

**Comment by robsyme** [comment]
For future reference, Daniel, you might consider adding in `return` instead of exit for this sort of debugging:

```groovy
workflow TEST{
    ch = channel.of(1, 2,3)
    ch.view()

    return
    // Other workflow code that I didn't want executing was after this line
}
```
