### ISSUE TITLE
Assistance Required for Error in “Nextflow for Newcomers” Tutorial (Part 3: Hello Genomic)

### ISSUE THREAD

**Issue by jeong2624** [nextflow-io/training#484]
I hope this message finds you well. I am currently studying the “Nextflow for Newcomers” tutorial and have encountered an issue in Part 3: Hello Genomic. The error I am facing is shown in the attached screenshot.

Unfortunately, I am unable to determine the cause of the issue or how to resolve it.

I would greatly appreciate it if you could provide some guidance on this matter. Please let me know if any additional information or logs are required.

Thank you for your support.

![image (1)](https://github.com/user-attachments/assets/197529fc-4ef3-46c8-a721-165b79a5bb63)
![image](https://github.com/user-attachments/assets/98fe8465-bf4b-4297-95b7-99844f1dbca9)

**Comment by robsyme** [comment]
Hi Jeong-Woon. This is a question about Nextflow rathe than the training materials specifically. Can you post your question on the [comunity forum](https://community.seqera.io)?

**Comment by jeong2624** [comment]
Hi, Robsyme. I just posted my question on the [Nextflow Community Forum](https://community.seqera.io/).
Could you please check it?
